### ISSUE TITLE
Inconsistency in calculations

### ISSUE THREAD

**Issue by frostbitten** [kazad/instacalc#84]
I was comparing products on amazon using this tool, copying and pasting some of the details into the calculator. I noticed it wasn't using a consistent format for the calculations and it seems to be based purely on the first number in the calculation (not the units of it, but rather arbitrary numbers).

Here's the exact calc `$25 / (18.9" x 15" x 21.7") in cents`

After noticing this behavior I copied the and pasted the line so it was exactly the same, and then modified just the first number in the calc to produce this screenshot of the inconsistency.

![image](https://github.com/kazad/instacalc/assets/593791/c496b40a-963d-4063-9bc5-2c63cf81393b)
Debug info for the correctly formatted lines:
![image](https://github.com/kazad/instacalc/assets/593791/29a36555-51d7-448b-a8a8-a1701c9c826b)

A workaround I found is to be a bit more specific when writing the calc, for instance: `$23 / (18.9" x 15" x 21.7") in cents/in` does get me to the `cents/in³` units I wanted

**Comment by kazad** [comment]
Thanks for the bug report! I couldn't reproduce it, but I've been doing some updates recently for $ symbol -> USD handling, and I wonder if you caught it partway. Here's what I see when I tried to repro just now:

https://instacalc.com/57430

<img width="764" alt="cents per cubic inch" src="https://github.com/kazad/instacalc/assets/115572/e6e63d51-d0d1-457c-a7e9-f6dbf181ff91">

Could you share a link to the calc with the problems above? I also wonder if there's some invisible characters I may need to filter out. Thanks for helping improve the site!

**Comment by frostbitten** [comment]
It seems like it's all good now! Cheers, and thanks for such a wonderful tool; no more awkward spreadsheets for my common, basic yet slightly complex calculations.

**Comment by kazad** [comment]
Glad it's working, and more than welcome! I wanted to make a friendlier spreadsheet interface, it's nice to hear when it's coming in handy.
